# Generated by Django 4.1 on 2023-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speak_box', models.CharField(max_length=500)),
                ('who_speaks', models.CharField(max_length=25)),
            ],
        ),
    ]
