# Generated by Django 4.1 on 2023-04-06 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='speak_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
