# Generated by Django 4.1 on 2023-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_speak_speak_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='who_speaks',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
