# Generated by Django 4.1 on 2023-04-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_speak_who_speaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='who_speaks',
            field=models.CharField(max_length=25),
        ),
    ]
